const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function fixture(){let user={id:'owner'},owner=true;const calls=[],removed=[];const client={auth:{getUser:async()=>({data:{user}})},rpc:async()=>({data:{is_owner:owner}}),functions:{invoke:async(name,args)=>{calls.push({name,args});return {error:{context:{json:async()=>({error:'Free AI not configured'})}}};}}};const window={ForgeScopeCore:{coreClient:async()=>client}};vm.runInNewContext(fs.readFileSync(__dirname+'/forgeAI.js','utf8'),{window,localStorage:{removeItem:k=>removed.push(k)},fetch:async(url,init)=>{calls.push({url,init});return {ok:true,json:async()=>({candidates:[]})};}});return {api:window.ForgeAI,calls,removed,setUser:(id,isOwner)=>{user=id?{id}:null;owner=isOwner;}};}
test('shared errors never use personal key or fall back to paid calls',async()=>{const f=fixture();await f.api.configure('personal','owner-secret');await f.api.configure('shared','');await assert.rejects(f.api.generate([{text:'test'}]),/Free AI not configured/);assert.equal(f.calls.length,1);assert.equal(f.calls[0].name,'forge-ai');assert.ok(!JSON.stringify(f.calls).includes('owner-secret'));});
test('member cannot select owner mode',async()=>{const f=fixture();f.setUser('member',false);await assert.rejects(f.api.configure('personal','secret'),/platform owner/);assert.equal(f.calls.length,0);});
test('account change erases the previous owner key',async()=>{const f=fixture();await f.api.configure('personal','owner-secret');f.setUser('member',false);await assert.rejects(f.api.generate([{text:'test'}]),/Free AI not configured/);assert.equal(f.api.mode,'auto');assert.ok(!JSON.stringify(f.calls).includes('owner-secret'));});
test('signed-out request cannot call either provider',async()=>{const f=fixture();await f.api.configure('personal','secret');f.setUser(null,false);await assert.rejects(f.api.generate([]),/Sign in/);assert.equal(f.calls.length,0);});
test('owner explicit personal mode calls only personal Gemini',async()=>{const f=fixture();await f.api.configure('personal','secret');await f.api.generate([{text:'test'}]);assert.equal(f.calls[0].init.headers['x-goog-api-key'],'secret');assert.equal(f.calls[0].name,undefined);assert.deepEqual(f.removed,['forgeScopeGeminiApiKey']);});



test('owner defaults to saved account connection',async()=>{const f=fixture();await assert.rejects(f.api.generate([{text:'test'}]));assert.equal(f.calls[0].name,'forge-owner-ai');assert.equal(f.calls[0].args.body.action,'generate');});
test('member automatic mode calls only shared AI',async()=>{const f=fixture();f.setUser('member',false);await assert.rejects(f.api.generate([{text:'test'}]));assert.equal(f.calls[0].name,'forge-ai');});
test('empty temporary key does not change selected connection',async()=>{const f=fixture();await assert.rejects(f.api.configure('personal',''),/Enter a Gemini key/);assert.equal(f.api.mode,'auto');});
